---
langs: [fr_FR]
baseurl: "/plugin-trafficmirror" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
permalink: /404.html
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
exclude:
- vendor
plugins:
- jekyll-paginate
- jekyll-seo-tag
title: "trafficmirror"
description: "Ceci est la documentation du plugin trafficmirror de la solution domotique Jeedom."
author: "benoit5672"
image: https://www.jeedom.com/site/logo.png
forum: https://community.jeedom.com/tags/plugin-trafficmirror
tagPlugin: plugin-trafficmirror
